import type { Metadata } from "next";
import { EditorialHero, NumberedList, PageFrame } from "@/components/editorial";
import { SectionHeading } from "@/components/section-heading";
import { team } from "@/lib/content";

export const metadata: Metadata = { title: "About", description: "Meet the senior, multidisciplinary studio behind Fifth Signal." };

export default function AboutPage() {
  return <PageFrame><EditorialHero eyebrow="About the studio" index="03 / About" title="Small by design. Broad where it matters." copy="Fifth Signal is a senior digital growth and AI studio for companies that want creative quality and commercial accountability in the same room." /><section className="about-manifesto section-pad"><div className="manifesto-mark">FS</div><div><span>Our point of view</span><h2>Growth is not a department. It is the result of a clear promise, a useful product, a visible brand, and a system that learns.</h2><p>That is why our team crosses traditional agency lines. The same people shaping the story understand how the experience will be built, discovered, measured, and improved.</p></div></section><section className="principles section-pad"><SectionHeading eyebrow="Principles" title="How we work." /><NumberedList items={[{title:"Senior people do the work",copy:"The people in the room are the people researching, designing, building, and optimizing the system."},{title:"Evidence before opinion",copy:"Taste matters, but customer insight, performance data, and a clear strategic argument keep the work honest."},{title:"Connected over siloed",copy:"We plan brand, product, technology, acquisition, content, analytics, and AI as one commercial system."},{title:"Useful over theatrical",copy:"We use new technology where it creates leverage, not where it merely creates a more impressive presentation."}]} /></section><section className="about-team section-pad"><SectionHeading eyebrow="The team" title="Different disciplines. One standard." /><div className="team-grid team-grid--large">{team.map(([name, role, initials], index) => <div className="team-card" key={name}><div className={`team-portrait portrait-${(index % 5) + 1}`}><span>{initials}</span><i /></div><h3>{name}</h3><p>{role}</p></div>)}</div></section><section className="location-band"><span>Berlin</span><h2>Working with ambitious teams worldwide.</h2><span>52.52° N · 13.40° E</span></section></PageFrame>;
}

