import type { Metadata } from "next";
import { PageFrame } from "@/components/editorial";

export const metadata: Metadata = { title: "Contact", description: "Start a conversation with Fifth Signal." };

export default function ContactPage() {
  return <PageFrame cta={false}><section className="contact-page"><div className="contact-intro"><span>05 / Contact</span><h1>Let’s build your next growth system.</h1><p>Tell us what you are building, where growth is getting stuck, and what a strong outcome would look like.</p><a href="mailto:hello@fifthsignal.studio">hello@fifthsignal.studio ↗</a></div><form className="contact-form" action="mailto:hello@fifthsignal.studio" method="post" encType="text/plain"><label><span>Your name</span><input name="name" type="text" autoComplete="name" required placeholder="Ada Lovelace" /></label><label><span>Work email</span><input name="email" type="email" autoComplete="email" required placeholder="ada@company.com" /></label><label><span>Company</span><input name="company" type="text" autoComplete="organization" placeholder="Company name" /></label><fieldset><legend>What can we help with?</legend><div className="form-options">{["Brand & website", "SEO & AI search", "Content & paid", "AI & automation", "Analytics & CRO", "Embedded team"].map(item => <label key={item}><input type="checkbox" name="interest" value={item} /><span>{item}</span></label>)}</div></fieldset><label><span>What are you trying to achieve?</span><textarea name="brief" required rows={5} placeholder="A little context, the important constraint, and what success looks like…" /></label><label><span>Indicative investment</span><select name="budget" defaultValue=""><option value="" disabled>Select a range</option><option>€15k–€30k</option><option>€30k–€60k</option><option>€60k–€120k</option><option>€120k+</option></select></label><button className="form-submit" type="submit">Send project brief <span>↗</span></button><small>Submitting opens your email client. No form data is stored by this private prototype.</small></form></section></PageFrame>;
}

