import { ChartNoAxesCombined, Handshake, Info, ListOrdered, PackageCheck, SlidersHorizontal, Target } from "lucide-react";
import { CtaButton } from "@/components/cta-button";
import { Faq } from "@/components/faq";
import { FinalCta } from "@/components/final-cta";
import { OfferOverview } from "@/components/offer-overview";
import { Reveal } from "@/components/reveal";
import { SectionHeading } from "@/components/section-heading";
import { WorkRibbon } from "@/components/work-ribbon";
import { getFaqs, getProjects } from "@/lib/content";
import { localizePath, t, type Locale } from "@/lib/i18n";

export function HomePage({ locale }: { locale: Locale }) {
  const projects = getProjects(locale);
  const faqs = getFaqs(locale);
  const description = locale === "de" ? "Wir entwickeln Websites, Apps und digitale Produkte, verbessern Sichtbarkeit und Conversion, setzen Paid Campaigns um und automatisieren Abläufe – als fokussierte Zusammenarbeit oder integrierte Partnerschaft." : "We build websites, apps, and digital products, improve visibility and conversion, run paid campaigns, and automate workflows—as a focused engagement or an integrated partnership.";
  const benefits = locale === "de" ? [
    [Handshake, "Eine klare Verantwortung", "Strategie, Umsetzung, Technologie und Performance werden gemeinsam gesteuert – mit einem festen Ansprechpartner für den gesamten Auftrag."],
    [SlidersHorizontal, "An deinen Prioritäten ausgerichtet", "Wir konzentrieren uns auf die Chancen und Engpässe, die für dein Unternehmen am wichtigsten sind, statt dir eine feste Leistungsliste aufzuzwingen."],
    [ChartNoAxesCombined, "Klare Entscheidungen, sichtbarer Fortschritt", "Du weißt jederzeit, woran wir arbeiten, warum es wichtig ist und was uns die Daten zeigen."],
  ] as const : [
    [Handshake, "Clear accountability", "Strategy, execution, technology, and performance are managed together, with one point of contact throughout the engagement."],
    [SlidersHorizontal, "Built around your priorities", "We focus on the opportunities and bottlenecks that matter most to your business, rather than forcing a fixed list of services."],
    [ChartNoAxesCombined, "Clear decisions, visible progress", "You always know what we are working on, why it matters, and what the data is telling us."],
  ] as const;
  const steps = locale === "de" ? [[Target, "Abstimmen", "Wir stimmen Ziele, aktuelle Herausforderungen, Erfolgskriterien und wirtschaftliche Prioritäten ab."], [ListOrdered, "Priorisieren", "Wir identifizieren die wertvollsten Chancen und verwandeln sie in einen praxisnahen, priorisierten Fahrplan."], [PackageCheck, "Umsetzen", "Wir arbeiten in fokussierten Zyklen, teilen Fortschritte transparent und passen die Richtung an, wenn neue Erkenntnisse entstehen."]] as const : [[Target, "Align", "We agree on your goals, current challenges, success measures, and commercial priorities."], [ListOrdered, "Prioritize", "We identify the most valuable opportunities and turn them into a practical, sequenced roadmap."], [PackageCheck, "Deliver", "We work in focused cycles, share progress clearly, and adjust direction as new evidence emerges."]] as const;
  const title = locale === "de" ? <>Entwickelt für <br /><em>profitables</em> Wachstum.</> : <>Engineered for <br /><em>profitable</em> growth.</>;
  return <main id="main-content" className="home-page">
    <section id="intro" className="hero hero--home grid [place-items:start_center] px-page pt-32 pb-section"><div className="hero-inner flex w-full max-w-[58rem] flex-col items-center text-center"><h1 className="shiny-text mt-6 mb-6 w-full max-w-hero text-display-lg font-semibold">{title}</h1><p className="hero-copy m-0 max-w-narrow text-lead font-medium text-muted">{description}</p><div className="hero-actions mt-8 flex gap-3 max-[600px]:w-[min(270px,100%)] max-[600px]:flex-col"><CtaButton href={localizePath("/contact", locale)}>{t(locale, "Book a consultation")}</CtaButton><CtaButton href={localizePath("/work", locale)} light>{t(locale, "Explore our work")}</CtaButton></div></div></section>
    <section id="solutions" className="service-category-section pt-section pb-section"><WorkRibbon projects={projects} locale={locale} label={t(locale, "Selected work")} /><div className="px-page"><p className="mx-auto mt-6 flex w-fit max-w-4xl items-start gap-3 rounded-card border border-[#bfd2f7] border-l-4 border-l-[var(--wave-blue)] bg-[#edf3ff] px-4 py-3 text-small text-[#555550]"><Info className="mt-0.5 size-4 shrink-0 text-[var(--wave-blue)]" /><span>{locale === "de" ? "Diese Projekte sind fiktive Konzepte und dienen ausschließlich zur Veranschaulichung von UI und Design. Sie stellen keine realen Kundenprojekte dar." : "These projects are fictional concepts shown solely for UI and design illustration. They do not represent real client work."}</span></p></div><div className="px-page pt-section-compact"><SectionHeading title={locale === "de" ? "Starte mit dem, was jetzt zählt." : "Start with what matters now."} copy={locale === "de" ? "Entdecke vier Wege der Zusammenarbeit und finde heraus, welcher zu deiner aktuellen Priorität passt." : "Explore four ways to work together and find the one that fits your current priority."} align="center" /></div><div className="px-page pt-section-compact"><OfferOverview locale={locale} /></div></section>
    <section id="why" className="px-page py-section"><SectionHeading title={t(locale, "Why Webpilot")} align="center" /><div className="benefit-grid grid grid-cols-6 gap-4 max-[900px]:grid-cols-1">{benefits.map(([Icon, heading, copy], index) => <Reveal className={`benefit-card benefit-card-${index + 1} col-span-2 px-6 pt-3 pb-6 text-center`} delay={index * 50} key={heading}><div className="benefit-visual grid place-items-center"><Icon className="size-[42px]" strokeWidth={1.7} /></div><h3 className="mt-6 mb-2 text-heading-sm font-semibold">{heading}</h3><p className="m-0 text-body text-muted">{copy}</p></Reveal>)}</div></section>
    <section id="process" className="px-page py-section"><SectionHeading title={t(locale, "How the work moves forward")} copy={t(locale, "A straightforward three-stage process with clear priorities from the beginning.")} align="center" /><ol className="process-list mx-auto grid max-w-[62rem] grid-cols-3 gap-4 pt-[52px] max-[900px]:grid-cols-1">{steps.map(([Icon, heading, copy], index) => <li className="process-step relative rounded-card bg-surface p-6 shadow-surface" key={heading}><span className="process-node absolute -top-[52px] left-[calc(50%_-_19px)] grid size-[38px] place-items-center rounded-full bg-[#111] text-white">{index + 1}</span><Icon className="size-[42px]" strokeWidth={1.7} /><div className="pt-7"><h3 className="mb-2 text-heading-sm font-semibold">{heading}</h3><p className="text-body text-muted">{copy}</p></div></li>)}</ol></section>
    <section id="faq" className="faq-section px-page py-section"><SectionHeading title="FAQs" align="center" /><div className="mx-auto max-w-[820px]"><Faq items={faqs} id={`home-faq-${locale}`} /></div></section><FinalCta locale={locale} />
  </main>;
}
