import { FinalCta } from "@/components/final-cta";
import { ProjectCard } from "@/components/project-card";
import { ProjectVisual } from "@/components/project-visual";
import { SectionHeading } from "@/components/section-heading";
import type { ProjectEntry } from "@/lib/content";
import type { Locale } from "@/lib/i18n";

export function WorkDetailPage({ locale, project, related }: { locale: Locale; project: ProjectEntry; related: ProjectEntry[] }) {
  const p = project.data;
  return <main id="main-content"><article className="case-study"><header className="case-hero px-page pt-[5.75rem] text-center"><h1 className="mx-auto mt-16 mb-6 max-w-hero text-display-sm font-semibold">{p.title}</h1><p className="mx-auto max-w-narrow text-lead font-medium text-muted">{p.summary}</p><div className="case-visual-wrap mt-20 h-[760px] overflow-hidden rounded-card max-[900px]:h-[560px] max-[600px]:h-[430px] [&_.project-visual]:h-full"><ProjectVisual project={p} /></div></header><section className="case-summary grid grid-cols-[1.5fr_1fr_1fr] gap-3 px-page pt-6 pb-section-compact max-[900px]:grid-cols-2 max-[600px]:grid-cols-1"><div className="flex min-h-[210px] flex-col rounded-card bg-surface p-6 shadow-surface max-[900px]:col-span-full"><span className="text-caption text-[#888]">{locale === "de" ? "Ergebnis" : "Result"}</span><strong className="mt-auto text-display-sm font-semibold tabular-nums">{p.metric}</strong><p className="mt-auto text-body text-[#555]">{p.metricLabel}</p></div><div className="flex min-h-[210px] flex-col rounded-card bg-surface p-6 shadow-surface"><span className="text-caption text-[#888]">{locale === "de" ? "Zeitraum" : "Timeline"}</span><h2 className="mt-auto text-heading-md font-semibold">{p.timeline}</h2></div><div className="flex min-h-[210px] flex-col rounded-card bg-surface p-6 shadow-surface"><span className="text-caption text-[#888]">{locale === "de" ? "Leistungen" : "Services"}</span><p className="mt-auto text-body text-[#555]">{p.categories.join(", ")}</p></div></section>
      <section className="case-narrative px-page py-section-compact">{[[locale === "de" ? "Herausforderung" : "Challenge", p.challenge], [locale === "de" ? "Strategie" : "Strategy", p.strategy], [locale === "de" ? "Umsetzung" : "Execution", p.execution]].map(([label, copy], index) => <div className="grid grid-cols-[180px_1fr] gap-12 border-t border-line py-12 max-[600px]:grid-cols-1 max-[600px]:gap-4" key={label}><span className="text-caption tabular-nums text-[#777]">0{index + 1} · {label}</span>{index === 0 ? <h2 className="m-0 text-heading-md font-semibold">{copy}</h2> : <p className="m-0 max-w-reading text-body-lg text-[#555]">{copy}</p>}</div>)}</section><section className="case-tools mx-auto grid max-w-layout grid-cols-[200px_1fr] border-b border-line py-section-compact max-[600px]:grid-cols-1 max-[600px]:gap-6"><span className="text-label font-medium uppercase">{locale === "de" ? "Eingesetzte Technologie" : "Technology used"}</span><div className="flex flex-wrap gap-2">{p.tools.map((tool) => <i className="rounded-xl border border-[#ccc] px-[13px] py-[9px] text-caption not-italic" key={tool}>{tool}</i>)}</div></section></article>
    <section className="related-work px-page py-section"><SectionHeading title={locale === "de" ? "Weitere Fallstudien" : "Next case studies"} align="center" /><div className="related-grid grid grid-cols-3 gap-4 max-[900px]:grid-cols-1">{related.map(({ data }) => <ProjectCard project={data} locale={locale} key={data.slug} />)}</div></section><FinalCta locale={locale} /></main>;
}
