import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageFrame } from "@/components/editorial";
import { getInsight, insights } from "@/lib/content";

export function generateStaticParams() { return insights.map(article => ({ article: article.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ article: string }> }): Promise<Metadata> { const { article: slug } = await params; const article = getInsight(slug); return article ? { title: article.title, description: article.excerpt } : {}; }

export default async function InsightPage({ params }: { params: Promise<{ article: string }> }) {
  const { article: slug } = await params; const article = getInsight(slug); if (!article) notFound();
  return <PageFrame><article className="article-page"><header><Link href="/insights">← All insights</Link><div><span>{article.category}</span><span>{article.date} · {article.read}</span></div><h1>{article.title}</h1><p>{article.excerpt}</p></header><div className="article-figure"><span>WEBPILOT</span><i /><i /><b>{article.category}</b></div><div className="article-body"><aside>In brief</aside><div><p className="article-lede">The old boundaries between brand, product, acquisition, content, and operations are becoming less useful. Customers experience one company, and intelligent systems increasingly evaluate the same combined evidence.</p><h2>Start with the decision, not the channel</h2><p>Good systems begin by naming the business decision they need to improve. That might be choosing a clearer market position, earning more qualified discovery, responding to demand faster, or giving a team back time. Channels and tools follow from that decision.</p><p>When teams start with a platform or trend, they often create activity without leverage. When they start with a constrained outcome, the right mix of story, experience, evidence, distribution, and automation becomes much easier to see.</p><blockquote>Connected growth is less about doing everything. It is about making every important part reinforce the next.</blockquote><h2>Build evidence that can travel</h2><p>A strong claim should be visible in product behavior, customer stories, structured data, sales conversations, and the content a model or search engine retrieves. Repetition alone is not authority; consistent, useful proof is.</p><h2>Design a learning loop</h2><p>The final layer is measurement. Define the signal, review it at a useful cadence, and decide what the team will change when it moves. A dashboard without a decision ritual is decoration.</p><p>This article is original placeholder editorial content created for the private Webpilot concept.</p></div></div></article></PageFrame>;
}
